"use client";

import { Button } from "@/components/ui/button";
import { DashboardHero } from "@/components/dashboard/dashboard-hero";
import { DashboardPage } from "@/components/dashboard/dashboard-page";
import { MetricCard } from "@/components/dashboard/metric-card";
import { Input } from "@/components/ui/input";
import { api } from "@/lib/api";
import { CheckCircle2, Copy, Globe2, Link2, Loader2, Plus, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

type Site = { id: number; name: string; domain: string | null; stack: string };
type Domain = { id:number; hostname:string; status:string; validation_name:string|null; validation_value:string|null; cname_target:string|null; last_error:string|null; verified_at:string|null; site:{id:number;name:string}|null };

const active = (domain: Domain) => domain.status === "active";

export default function DomainsPage() {
  const [domains, setDomains] = useState<Domain[]>([]);
  const [sites, setSites] = useState<Site[]>([]);
  const [hostname, setHostname] = useState("");
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<number | "create" | null>(null);
  const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = async () => { setLoading(true); try { const [domainResult, siteResult] = await Promise.all([api<{domains:Domain[]}>("/api/domains"),api<{sites:Site[]}>("/api/sites")]); setDomains(domainResult.domains);setSites(siteResult.sites); } catch (e) { setError(e instanceof Error?e.message:"Unable to load domains."); } finally { setLoading(false); } };
  useEffect(()=>{void load();},[]);
  const act = async (key:number|"create", action:()=>Promise<void>)=>{setBusy(key);setError("");setNotice("");try{await action();}catch(e){setError(e instanceof Error?e.message:"Something went wrong.");}finally{setBusy(null);}};
  const create = async (event:FormEvent)=>{event.preventDefault();await act("create",async()=>{const result=await api<{domain:Domain}>("/api/domains",{method:"POST",body:JSON.stringify({hostname})});setDomains(items=>[result.domain,...items]);setHostname("");setNotice("Domain added. Complete the DNS steps below, then check its status.");});};
  const copy = async (value:string)=>{await navigator.clipboard.writeText(value);setNotice("Copied.");};
  return <DashboardPage><DashboardHero eyebrow="Domain routing · HTTPS management" title="Domains" description="Connect a domain you already own to any hosted project. BerryPanel handles HTTPS once the connection is verified." icon={Globe2} contextValue="Domain routing" />
  <section className="grid gap-4 md:grid-cols-3">
    <MetricCard label="Domains" value={loading?"...":String(domains.length)} detail="managed hostnames" icon={Globe2} tone="lavender" />
    <MetricCard label="HTTPS Ready" value={loading?"...":String(domains.filter(active).length)} detail="verified domains" icon={ShieldCheck} tone="sky" />
    <MetricCard label="Connected" value={loading?"...":String(domains.filter(domain=>domain.site).length)} detail="attached projects" icon={Link2} tone="mist" />
  </section>
  <section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Add a domain</h2><p className="mt-1 text-sm text-[#567C8D]">Enter the address visitors will use, such as <span className="font-medium">app.yourcompany.com</span>.</p><form onSubmit={create} className="mt-5 flex flex-col gap-3 sm:flex-row"><Input required value={hostname} onChange={e=>setHostname(e.target.value)} placeholder="app.yourcompany.com" className="h-12"/><Button disabled={busy!==null} className="h-12 bg-[#2F4156]">{busy==="create"?<Loader2 className="animate-spin"/>:<Plus/>} Add domain</Button></form></section>
  {error&&<p className="rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{notice&&<p className="rounded-2xl bg-green-50 p-4 text-sm text-green-800">{notice}</p>}
  <section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Your domains</h2><p className="mt-1 text-sm text-[#567C8D]">Only verified domains can be connected to a project.</p></div><span className="rounded-full bg-[#F1F1F1] px-3 py-1 text-sm">{domains.length}</span></div>
  {loading?<div className="py-12 text-center text-sm text-[#567C8D]">Loading domains…</div>:domains.length===0?<div className="py-12 text-center text-sm text-[#567C8D]">No domains connected yet.</div>:<div className="mt-5 space-y-4">{domains.map(domain=><DomainCard key={domain.id} domain={domain} sites={sites} busy={busy===domain.id} onCopy={copy} onRefresh={()=>act(domain.id,async()=>{const result=await api<{domain:Domain}>(`/api/domains/${domain.id}/refresh`,{method:"POST",body:"{}"});setDomains(items=>items.map(item=>item.id===domain.id?result.domain:item));setNotice(result.domain.status==="active"?"Domain verified and ready.":"Still waiting for DNS verification. It can take a few minutes.");})} onAttach={(siteId)=>act(domain.id,async()=>{const result=await api<{domain:Domain}>(`/api/domains/${domain.id}/site`,{method:"PUT",body:JSON.stringify({site_id:siteId||null})});setDomains(items=>items.map(item=>item.id===domain.id?result.domain:item));setNotice(siteId?"Domain connected to the project.":"Domain disconnected from the project.");})} onDelete={()=>act(domain.id,async()=>{await api(`/api/domains/${domain.id}`,{method:"DELETE"});setDomains(items=>items.filter(item=>item.id!==domain.id));setNotice("Domain removed.");})}/>)}</div>}</section></DashboardPage>;
}

function DomainCard({domain,sites,busy,onCopy,onRefresh,onAttach,onDelete}:{domain:Domain;sites:Site[];busy:boolean;onCopy:(value:string)=>void;onRefresh:()=>void;onAttach:(siteId:string)=>void;onDelete:()=>void}) { const status=active(domain); return <article className="rounded-2xl border border-[#C8D9E6] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{domain.hostname}</h3><span className={`rounded-full px-2.5 py-1 text-xs ${status?"bg-green-100 text-green-800":"bg-amber-100 text-amber-800"}`}>{status?"Ready":"Needs setup"}</span></div><p className="mt-1 text-sm text-[#567C8D]">{domain.site?`Connected to ${domain.site.name}`:"Not connected to a project"}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" disabled={busy} onClick={onRefresh}>{busy?<Loader2 className="animate-spin"/>:<RefreshCw/>} Check status</Button><Button variant="ghost" size="icon" aria-label="Remove domain" disabled={busy} onClick={onDelete}><Trash2 className="size-4 text-red-600"/></Button></div></div>{!status&&<div className="mt-5 rounded-2xl bg-[#F1F1F1] p-4 text-sm"><p className="font-medium">Set up your DNS</p><p className="mt-1 text-[#567C8D]">Add this CNAME record at the company where you bought your domain:</p><Record label="Name" value={domain.hostname} copy={onCopy}/><Record label="Points to" value={domain.cname_target||"Contact support"} copy={onCopy}/>{domain.validation_name&&domain.validation_value&&<><p className="mt-4 text-[#567C8D]">Also add this TXT record to confirm you own the domain:</p><Record label="Name" value={domain.validation_name} copy={onCopy}/><Record label="Value" value={domain.validation_value} copy={onCopy}/></>}{domain.last_error&&<p className="mt-3 text-amber-800">{domain.last_error}</p>}</div>} {status&&<div className="mt-5 flex flex-col gap-2 sm:flex-row sm:items-center"><label className="text-sm font-medium">Project</label><select value={domain.site?.id??""} onChange={e=>onAttach(e.target.value)} disabled={busy} className="h-10 rounded-xl border border-input bg-background px-3 text-sm"><option value="">Choose a project</option>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select><span className="flex items-center gap-1 text-sm text-green-700"><CheckCircle2 className="size-4"/> HTTPS ready</span></div>}</article> }
function Record({label,value,copy}:{label:string;value:string;copy:(value:string)=>void}) { return <div className="mt-3 flex items-center justify-between gap-4 rounded-xl bg-white px-3 py-2"><span className="min-w-0 truncate"><span className="mr-2 text-xs text-[#567C8D]">{label}</span><span className="font-mono text-xs">{value}</span></span><button onClick={()=>copy(value)} className="shrink-0 text-[#567C8D]" aria-label={`Copy ${label}`}><Copy className="size-4"/></button></div> }
