<?php

return [
    'users_root' => env('BERRYPANEL_USERS_ROOT') ?: storage_path('app/berrypanel/users'),
    'server_ip' => env('BERRYPANEL_SERVER_IP'),
    'site_domain_suffix' => env('BERRYPANEL_SITE_DOMAIN_SUFFIX'),
    'site_url_scheme' => env('BERRYPANEL_SITE_URL_SCHEME', env('BERRYPANEL_SITE_DOMAIN_SUFFIX') ? 'https' : 'http'),
    'git_deploy_enabled' => (bool) env('BERRYPANEL_GIT_DEPLOY_ENABLED', false),
    'storage_quota_gb' => (int) env('BERRYPANEL_STORAGE_QUOTA_GB', 25),
    'site_command_use_sudo' => filter_var(env('BERRYPANEL_SITE_COMMAND_USE_SUDO', env('BERRYPANEL_USERS_ROOT') ? true : false), FILTER_VALIDATE_BOOLEAN),
    'nginx_provisioning_enabled' => (bool) env('BERRYPANEL_NGINX_PROVISIONING_ENABLED', false),
    'nginx_sites_available_path' => env('BERRYPANEL_NGINX_SITES_AVAILABLE_PATH', '/etc/nginx/sites-available'),
    'nginx_sites_enabled_path' => env('BERRYPANEL_NGINX_SITES_ENABLED_PATH', '/etc/nginx/sites-enabled'),
    'nginx_php_fpm_socket' => env('BERRYPANEL_NGINX_PHP_FPM_SOCKET', '/run/php/php8.4-fpm.sock'),
    'php_fpm_user' => env('BERRYPANEL_PHP_FPM_USER', 'www-data'),
    'ssh_provisioning_enabled' => (bool) env('BERRYPANEL_SSH_PROVISIONING_ENABLED', false),
    'ssh_host' => env('BERRYPANEL_SSH_HOST'),
    'ssh_port' => (int) env('BERRYPANEL_SSH_PORT', 22),
    'database_provisioning_enabled' => (bool) env('BERRYPANEL_DATABASE_PROVISIONING_ENABLED', false),
    'supervisor_enabled' => filter_var(env('BERRYPANEL_SUPERVISOR_ENABLED', false), FILTER_VALIDATE_BOOLEAN),
    'supervisor_config_path' => env('BERRYPANEL_SUPERVISOR_CONFIG_PATH', '/etc/supervisor/conf.d'),
    'node_port_base' => (int) env('BERRYPANEL_NODE_PORT_BASE', 12000),
    'cloudflare_api_token' => env('CLOUDFLARE_API_TOKEN'),
    'cloudflare_zone_id' => env('CLOUDFLARE_ZONE_ID'),
    'cloudflare_fallback_origin' => env('CLOUDFLARE_FALLBACK_ORIGIN'),
    'mysql_admin_host' => env('BERRYPANEL_MYSQL_ADMIN_HOST', '127.0.0.1'),
    'mysql_admin_port' => (int) env('BERRYPANEL_MYSQL_ADMIN_PORT', 3306),
    'mysql_admin_username' => env('BERRYPANEL_MYSQL_ADMIN_USERNAME', 'root'),
    'mysql_admin_password' => env('BERRYPANEL_MYSQL_ADMIN_PASSWORD', ''),
    'mysql_user_host' => env('BERRYPANEL_MYSQL_USER_HOST', 'localhost'),
];
