<?php
use App\Jobs\RunSiteDeployment; use App\Models\Deployment; use App\Models\Site; use App\Models\User; use App\Services\Hosting\RestrictedCommandExecutor; use App\Services\Hosting\SitePathResolver; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\File; use Illuminate\Support\Facades\Queue;
uses(RefreshDatabase::class);
function hybridSite(User $user,string $root):Site{File::ensureDirectoryExists($root.'/backend/public');File::ensureDirectoryExists($root.'/frontend');File::put($root.'/backend/artisan','');File::put($root.'/backend/composer.json','{}');File::put($root.'/frontend/package.json','{}');return Site::create(['user_id'=>$user->id,'name'=>'Hybrid App','slug'=>'hybrid-app','stack'=>'Node.js + Laravel','php_version'=>'8.4','status'=>'provisioned','root_path'=>$root,'public_path'=>$root.'/backend/public','repository_url'=>'https://github.com/example/hybrid','repository_branch'=>'main','backend_directory'=>'/backend','frontend_directory'=>'/frontend','laravel_public_directory'=>'/backend/public','domain'=>'app.example.test']);}
test('hybrid application directories are validated inside the site root',function(){$users=storage_path('framework/testing/hybrid-paths');File::deleteDirectory($users);config(['berrypanel.users_root'=>$users]);$user=User::factory()->create();$site=hybridSite($user,$users.'/user/sites/hybrid-app');$paths=app(SitePathResolver::class)->validateApplicationDirectories($site);expect($paths['backend'])->toEndWith('/backend')->and($paths['frontend'])->toEndWith('/frontend')->and($paths['public'])->toEndWith('/backend/public');});
test('restricted terminal rejects shell chaining before execution',function(){$users=storage_path('framework/testing/hybrid-terminal');File::deleteDirectory($users);config(['berrypanel.users_root'=>$users]);$user=User::factory()->create();$site=hybridSite($user,$users.'/user/sites/hybrid-app');expect(fn()=>app(RestrictedCommandExecutor::class)->run($site,$user,'git status; rm -rf /','root'))->toThrow(RuntimeException::class,'Shell chaining');});
test('another user cannot view hosting deployment history',function(){$users=storage_path('framework/testing/hybrid-auth');File::deleteDirectory($users);config(['berrypanel.users_root'=>$users]);$owner=User::factory()->create();$other=User::factory()->create();$site=hybridSite($owner,$users.'/user/sites/hybrid-app');$this->actingAs($other)->getJson("/api/sites/{$site->id}/deployments")->assertForbidden();});
test('an owner can retry a failed deployment as a new queued deployment',function(){Queue::fake();$users=storage_path('framework/testing/hybrid-retry');File::deleteDirectory($users);config(['berrypanel.users_root'=>$users]);$user=User::factory()->create();$site=hybridSite($user,$users.'/user/sites/hybrid-app');$failed=$site->deployments()->create(['triggered_by'=>$user->id,'status'=>'failed','branch'=>'main','failed_step'=>'node-build']);$this->actingAs($user)->postJson("/api/sites/{$site->id}/deployments/{$failed->id}/retry")->assertAccepted()->assertJsonPath('deployment.status','queued');expect(Deployment::where('site_id',$site->id)->count())->toBe(2);Queue::assertPushed(RunSiteDeployment::class);});

test('an owner can add an additional node service from a validated repository folder',function(){$users=storage_path('framework/testing/hybrid-additional-node');File::deleteDirectory($users);config(['berrypanel.users_root'=>$users]);$user=User::factory()->create();$site=hybridSite($user,$users.'/user/sites/hybrid-app');File::ensureDirectoryExists($site->root_path.'/ar');File::put($site->root_path.'/ar/package.json','{}');$this->actingAs($user)->postJson("/api/sites/{$site->id}/additional-node-services",['name'=>'AR service','working_directory'=>'/ar','start_command'=>'npm run start','install_command'=>'npm ci','build_command'=>'npm run build','internal_port'=>3001])->assertCreated()->assertJsonPath('service.name','AR service')->assertJsonPath('service.status','pending_deployment');expect($site->services()->where('name','AR service')->firstOrFail()->working_directory)->toBe('/ar');});

test('an additional node service requires a package json folder',function(){$users=storage_path('framework/testing/hybrid-invalid-additional-node');File::deleteDirectory($users);config(['berrypanel.users_root'=>$users]);$user=User::factory()->create();$site=hybridSite($user,$users.'/user/sites/hybrid-app');File::ensureDirectoryExists($site->root_path.'/ar');$this->actingAs($user)->postJson("/api/sites/{$site->id}/additional-node-services",['name'=>'AR service','working_directory'=>'/ar','start_command'=>'npm run start'])->assertUnprocessable()->assertJsonPath('message','Additional Node.js directory must contain package.json.');});

//test
