<?php
namespace App\Services\Hosting;
use App\Models\SiteService; use Illuminate\Support\Facades\File; use RuntimeException; use Symfony\Component\Process\Process;
class SupervisorManager {
 public function __construct(private SitePathResolver $paths){}
 public function apply(SiteService $service):void{if(!config('berrypanel.supervisor_enabled'))return;$site=$service->site()->firstOrFail();$cwd=$this->paths->directory($site,$service->working_directory);$this->validateCommand($service->command,$service->type);$name='berrypanel-'.$site->id.'-'.$service->id;$tmp=storage_path("app/berrypanel/supervisor/{$name}.conf");File::ensureDirectoryExists(dirname($tmp));File::put($tmp,$this->config($name,$site->user->linux_username,$cwd,$service));$target=rtrim(config('berrypanel.supervisor_config_path'),'/')."/{$name}.conf";$this->run(['sudo','cp',$tmp,$target]);$this->run(['sudo','supervisorctl','reread']);$this->run(['sudo','supervisorctl','update']);}
 public function action(SiteService $service,string $action):void{if(!in_array($action,['start','stop','restart']))throw new RuntimeException('Unsupported service action.');if(config('berrypanel.supervisor_enabled'))$this->run(['sudo','supervisorctl',$action,'berrypanel-'.$service->site_id.'-'.$service->id.':*']);$service->update(['status'=>$action==='stop'?'stopped':'running','last_started_at'=>$action!=='stop'?now():$service->last_started_at,'last_stopped_at'=>$action==='stop'?now():$service->last_stopped_at,'restart_count'=>$action==='restart'?$service->restart_count+1:$service->restart_count]);}
 public function validateCommand(string $command,string $type):void{$patterns=['queue'=>'/^php artisan queue:work(?: --[a-z-]+(?:=\S+)?)*$/','horizon'=>'/^php artisan horizon$/','reverb'=>'/^php artisan reverb:start$/','scheduler'=>'/^php artisan schedule:work$/','node'=>'/^(npm run (start|serve)|yarn (start|serve)|pnpm run (start|serve))$/'];if(!isset($patterns[$type])||!preg_match($patterns[$type],$command))throw new RuntimeException('Service command does not match an approved template.');}
 private function config(string $name,string $user,string $cwd,SiteService $s):string{$log=$s->log_file?:storage_path("logs/services/{$name}.log");return "[program:{$name}]\nprocess_name=%(program_name)s_%(process_num)02d\ncommand={$s->command}\ndirectory={$cwd}\nuser={$user}\nnumprocs={$s->processes}\nautostart=".($s->enabled?'true':'false')."\nautorestart=".($s->restart_policy==='never'?'false':'unexpected')."\nstartretries={$s->max_retries}\nstopwaitsecs={$s->stop_timeout}\nredirect_stderr=true\nstdout_logfile={$log}\nstopasgroup=true\nkillasgroup=true\n";}
 private function run(array $argv):void{$p=new Process($argv);$p->setTimeout(60);$p->run();if(!$p->isSuccessful())throw new RuntimeException(trim($p->getErrorOutput())?:'Supervisor command failed.');}
}
