"use client";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { api } from "@/lib/api"; import { deploymentEcho } from "@/lib/realtime"; import { useParams } from "next/navigation"; import { useEffect,useState } from "react"; import { Activity,Box,Download,FileKey2,GitBranch,Globe2,History,Play,RefreshCw,RotateCcw,ServerCog,Terminal as TerminalIcon } from "lucide-react";
type Site=Record<string,unknown>&{id:number;name:string;status:string;repository_url:string;repository_branch:string;backend_directory:string;frontend_directory:string;laravel_public_directory:string;node_version:string;package_manager:string;node_install_command:string;node_build_command:string;node_start_command:string;php_version:string;domain:string;health_check_url:string|null;deployment_timeout:number;ssl_enabled:boolean;migrate_on_deploy:boolean;build_on_deploy:boolean;restart_services_on_deploy:boolean};
type Deployment={id:number;status:string;commit_hash:string|null;branch:string;started_at:string|null;ended_at:string|null;failed_step:string|null}; type Service={id:number;name:string;type:string;command:string;status:string;enabled:boolean;restart_count:number};
type DeploymentLog={id:number;step:string;level:string;message:string;exit_code:number|null;logged_at:string};
const tabs=["Overview","Environment","Terminal","Deployments","Domain"] as const; type Tab=(typeof tabs)[number] | "Settings" | "Services";
const fieldClass="h-11 rounded-xl border-black/10";
export default function HostingPage(){const {siteId}=useParams<{siteId:string}>();const [site,setSite]=useState<Site|null>(null),[tab,setTab]=useState<Tab>("Overview"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[deployments,setDeployments]=useState<Deployment[]>([]),[services,setServices]=useState<Service[]>([]),[envScope,setEnvScope]=useState<"laravel"|"node">("laravel"),[envContent,setEnvContent]=useState(""),[command,setCommand]=useState("git status"),[scope,setScope]=useState("root"),[output,setOutput]=useState(""),[selectedDeployment,setSelectedDeployment]=useState<Deployment|null>(null),[deploymentLogs,setDeploymentLogs]=useState<DeploymentLog[]>([]),[logsLoading,setLogsLoading]=useState(false);
 const load=async()=>{try{const [s,d,v]=await Promise.all([api<{site:Site}>(`/api/sites/${siteId}`),api<{deployments:{data:Deployment[]}}>(`/api/sites/${siteId}/deployments`),api<{services:Service[]}>(`/api/sites/${siteId}/services`)]);setSite(s.site);setDeployments(d.deployments.data);setServices(v.services);const failed=d.deployments.data.find(item=>item.status==="failed");if(failed){setTab("Deployments");void openDeploymentLogs(failed)}}catch(e){setError(e instanceof Error?e.message:"Unable to load hosting project")}};
 // The route id is the only input to the initial project load.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{load()},[siteId]);
 useEffect(()=>{const echo=deploymentEcho();if(!echo)return;const channel=echo.private(`hosting.site.${siteId}`);channel.listen(".deployment.updated",(event:{deployment:Deployment})=>{setDeployments(current=>{const exists=current.some(item=>item.id===event.deployment.id);return exists?current.map(item=>item.id===event.deployment.id?event.deployment:item):[event.deployment,...current]});setSelectedDeployment(current=>current?.id===event.deployment.id?event.deployment:current)});channel.listen(".deployment.log.created",(event:{log:DeploymentLog})=>{setDeploymentLogs(current=>current.some(item=>item.id===event.log.id)?current:current.concat(event.log))});return()=>{echo.leave(`hosting.site.${siteId}`)}},[siteId]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError("");setNotice("");try{await fn()}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}};
 const save=()=>site&&act(async()=>{const {id,name,status,...payload}=site;void id;void name;void status;await api(`/api/sites/${siteId}/hosting-settings`,{method:"PUT",body:JSON.stringify(payload)});setNotice("Deployment settings saved.")});
 const deploy=()=>act(async()=>{await api(`/api/sites/${siteId}/deployments`,{method:"POST",body:"{}"});setNotice("Deployment queued.");await load()});
 const saveEnv=()=>act(async()=>{await api(`/api/sites/${siteId}/environments`,{method:"PUT",body:JSON.stringify({scope:envScope,content:envContent})});setNotice(`${envScope} environment saved securely.`)});
 const run=()=>act(async()=>{const r=await api<{result:{output:string;exit_code:number}}>(`/api/sites/${siteId}/terminal`,{method:"POST",body:JSON.stringify({command,scope,confirmed:command.includes("migrate")})});setOutput(`${r.result.output}\n\nExit code: ${r.result.exit_code}`)});
 const openDeploymentLogs=async(deployment:Deployment)=>{setLogsLoading(true);try{const response=await api<{deployment:Deployment;logs:DeploymentLog[]}>(`/api/sites/${siteId}/deployments/${deployment.id}/logs`);setSelectedDeployment(response.deployment);setDeploymentLogs(response.logs);setDeployments(current=>current.map(item=>item.id===deployment.id?response.deployment:item))}catch(e){setError(e instanceof Error?e.message:"Unable to load deployment logs")}finally{setLogsLoading(false)}};
 const downloadLogs=()=>{if(!selectedDeployment)return;const content=deploymentLogs.map(log=>`[${log.logged_at}] [${log.level.toUpperCase()}] [${log.step}] ${log.message}${log.exit_code!==null?` (exit ${log.exit_code})`:""}`).join("\n");const url=URL.createObjectURL(new Blob([content],{type:"text/plain"}));const link=document.createElement("a");link.href=url;link.download=`deployment-${selectedDeployment.id}.log`;link.click();URL.revokeObjectURL(url)};
 const retryDeployment=()=>selectedDeployment&&act(async()=>{const response=await api<{deployment:Deployment}>(`/api/sites/${siteId}/deployments/${selectedDeployment.id}/retry`,{method:"POST",body:"{}"});setDeployments(current=>[response.deployment,...current]);setSelectedDeployment(response.deployment);setDeploymentLogs([]);setNotice(`Deployment #${response.deployment.id} queued as a retry.`)});
 if(!site)return <div className="rounded-3xl bg-white p-8">{error||"Loading hosting project..."}</div>;
 const update=(key:keyof Site,value:unknown)=>setSite({...site,[key]:value});
 return <div className="space-y-6 text-[#121212]"><section className="rounded-3xl bg-white p-6 shadow-sm lg:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="rounded-full bg-[#d8cef2] px-4 py-2 text-sm">Node.js + Laravel</span><h1 className="mt-5 text-4xl font-semibold md:text-6xl">{site.name}</h1><p className="mt-3 text-[#666]">{site.repository_branch} · {site.domain}</p></div><div className="flex gap-2">{selectedDeployment?.status==="failed"&&<Button disabled={busy} variant="outline" onClick={retryDeployment} className="rounded-full px-6"><RotateCcw/>Retry</Button>}<Button disabled={busy} onClick={deploy} className="rounded-full bg-black px-6"><Play/>Deploy now</Button></div></div><div className="mt-8 flex gap-2 overflow-x-auto">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${tab===x?"bg-black text-white":"bg-[#f2f2f2]"}`}>{x}</button>)}</div></section>
 {error&&<p className="rounded-2xl bg-red-50 p-4 text-red-700">{error}</p>}{notice&&<p className="rounded-2xl bg-green-50 p-4 text-green-700">{notice}</p>}
 {tab==="Overview"&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[[Activity,"Deployment",site.status],[GitBranch,"Branch",site.repository_branch],[ServerCog,"Laravel",site.backend_directory],[Box,"Node.js",site.frontend_directory],[Globe2,"Domain",site.domain],[FileKey2,"SSL",site.ssl_enabled?"Enabled":"Disabled"],[History,"Deployments",String(deployments.length)],[ServerCog,"Services",`${services.filter(s=>s.status==="running").length} running`]].map(([Icon,label,value])=><div key={String(label)} className="rounded-3xl bg-white p-6 shadow-sm"><Icon className="size-5"/><p className="mt-6 text-sm text-[#777]">{String(label)}</p><p className="mt-1 truncate text-xl font-semibold">{String(value)}</p></div>)}</div>}
 {tab==="Settings"&&<Panel title="Repository & deployment settings"><div className="grid gap-5 md:grid-cols-2">{([['repository_url','Repository URL'],['repository_branch','Production branch'],['backend_directory','Laravel backend directory'],['frontend_directory','Node.js frontend directory'],['laravel_public_directory','Laravel public directory'],['node_version','Node.js version'],['package_manager','Package manager'],['node_install_command','Install command'],['node_build_command','Build command'],['node_start_command','Start command'],['php_version','PHP version'],['deployment_timeout','Timeout (seconds)']] as [keyof Site,string][]).map(([k,l])=><Field key={k} label={l} value={String(site[k]??"")} onChange={v=>update(k,k==="deployment_timeout"?Number(v):v)}/>)}</div><Checks site={site} update={update}/><Button className="mt-6 rounded-full" disabled={busy} onClick={save}>Save settings</Button></Panel>}
 {tab==="Environment"&&<Panel title="Environment variables"><div className="mb-4 flex gap-2"><Button variant={envScope==="laravel"?"default":"outline"} onClick={()=>setEnvScope("laravel")}>Laravel .env</Button><Button variant={envScope==="node"?"default":"outline"} onClick={()=>setEnvScope("node")}>Node.js .env</Button></div><p className="mb-3 text-sm text-[#666]">Paste KEY=value lines. Values are encrypted in storage, written with mode 0600, and redacted from logs.</p><textarea value={envContent} onChange={e=>setEnvContent(e.target.value)} className="min-h-80 w-full rounded-2xl border border-black/10 bg-[#111] p-5 font-mono text-sm text-green-300" placeholder="APP_ENV=production"/><Button className="mt-4 rounded-full" onClick={saveEnv}>Import and save</Button></Panel>}
 {tab==="Terminal"&&<Panel title="Restricted terminal"><p className="mb-4 text-sm text-[#666]">Approved commands only. No shell chaining, substitutions, redirects, traversal, or privileged commands.</p><div className="flex flex-col gap-3 md:flex-row"><select className="rounded-xl border p-3" value={scope} onChange={e=>setScope(e.target.value)}><option value="root">Repository</option><option value="laravel">Laravel</option><option value="node">Node.js</option></select><Input className={fieldClass} value={command} onChange={e=>setCommand(e.target.value)}/><Button onClick={run}><TerminalIcon/>Run</Button></div><pre className="mt-5 min-h-64 overflow-auto rounded-2xl bg-[#111] p-5 text-sm text-green-300">{output||"Command output will appear here."}</pre></Panel>}
 {tab==="Services"&&<Panel title="Persistent services"><div className="space-y-3">{services.length===0&&<p className="text-[#777]">No services configured. Use the API templates to add Queue Worker, Horizon, Reverb, Scheduler, or Node.js Server.</p>}{services.map(s=><div key={s.id} className="flex items-center justify-between rounded-2xl border p-4"><div><p className="font-medium">{s.name}</p><p className="font-mono text-xs text-[#777]">{s.command}</p></div><span className="rounded-full bg-[#f2f2f2] px-3 py-1 text-xs">{s.status} · {s.restart_count} restarts</span></div>)}</div></Panel>}
 {tab==="Deployments"&&<Panel title="Deployment history"><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-3">{deployments.map(d=><button type="button" onClick={()=>void openDeploymentLogs(d)} key={d.id} className={`w-full rounded-2xl border p-4 text-left ${selectedDeployment?.id===d.id?"border-black bg-[#f7f7f7]":"border-black/10"}`}><div className="flex items-center justify-between"><span className="font-medium">Deployment #{d.id}</span><span className={`rounded-full px-3 py-1 text-xs ${d.status==="failed"?"bg-red-100 text-red-700":d.status==="succeeded"?"bg-green-100 text-green-700":"bg-amber-100 text-amber-700"}`}>{d.status}</span></div><p className="mt-2 font-mono text-xs text-[#666]">{d.commit_hash?.slice(0,8)||d.branch}</p>{d.failed_step&&<p className="mt-2 text-sm text-red-700">Failed at: {d.failed_step}</p>}</button>)}</div><div className="min-h-96 rounded-2xl bg-[#111] p-4 text-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 pb-3"><div><p className="font-medium">{selectedDeployment?`Deployment #${selectedDeployment.id} logs`:"Deployment logs"}</p>{selectedDeployment?.failed_step&&<p className="text-xs text-red-300">Failed step: {selectedDeployment.failed_step}</p>}</div><div className="flex gap-2"><Button size="sm" variant="outline" disabled={!selectedDeployment||logsLoading} onClick={()=>selectedDeployment&&void openDeploymentLogs(selectedDeployment)}><RefreshCw className={logsLoading?"animate-spin":""}/>Refresh</Button><Button size="sm" variant="outline" disabled={!deploymentLogs.length} onClick={downloadLogs}><Download/>Download</Button></div></div><div className="mt-4 max-h-[32rem] space-y-2 overflow-auto font-mono text-xs">{!selectedDeployment&&<p className="text-white/50">Select a deployment to see exactly what happened.</p>}{selectedDeployment&&deploymentLogs.length===0&&!logsLoading&&<p className="text-white/50">No logs were recorded. Confirm the queue worker is running and inspect the failed_jobs table.</p>}{deploymentLogs.map(log=><div key={log.id} className={log.level==="error"?"text-red-300":"text-green-200"}><span className="text-white/40">[{new Date(log.logged_at).toLocaleTimeString()}]</span> <span className="text-blue-300">[{log.step}]</span> {log.message}{log.exit_code!==null&&<span className="text-amber-300"> exit={log.exit_code}</span>}</div>)}</div></div></div></Panel>}
 {tab==="Domain"&&<Panel title="Domain, SSL & health"><div className="grid gap-5 md:grid-cols-2"><Field label="Domain or subdomain" value={site.domain} onChange={v=>update('domain',v)}/><Field label="Health-check URL" value={site.health_check_url||""} onChange={v=>update('health_check_url',v)}/></div><Checks site={site} update={update}/><Button className="mt-6 rounded-full" onClick={save}>Save domain settings</Button></Panel>}</div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-3xl bg-white p-6 shadow-sm lg:p-8"><h2 className="mb-6 text-2xl font-semibold">{title}</h2>{children}</section>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div><Label className="mb-2">{label}</Label><Input className={fieldClass} value={value} onChange={e=>onChange(e.target.value)}/></div>}
function Checks({site,update}:{site:Site;update:(k:keyof Site,v:unknown)=>void}){return <div className="mt-5 grid gap-3 md:grid-cols-2">{([['ssl_enabled','Enable SSL'],['migrate_on_deploy','Run migrations'],['build_on_deploy','Build frontend'],['restart_services_on_deploy','Restart services']] as [keyof Site,string][]).map(([k,l])=><label key={k} className="flex items-center gap-3 rounded-xl bg-[#f7f7f7] p-4"><input type="checkbox" checked={Boolean(site[k])} onChange={e=>update(k,e.target.checked)}/>{l}</label>)}</div>}
