"use client";

import { CustomerServiceControls } from "@/components/hosting/customer-service-controls";
import { DashboardHero } from "@/components/dashboard/dashboard-hero";
import { DashboardPage } from "@/components/dashboard/dashboard-page";
import { MetricCard } from "@/components/dashboard/metric-card";
import { availabilityDetail, availabilityLabel } from "@/components/dashboard/availability-pill";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { api } from "@/lib/api";
import { deploymentEcho } from "@/lib/realtime";
import { Activity, Download, GitBranch, Globe2, Play, RefreshCw, RotateCcw, Terminal } from "lucide-react";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import type { SiteAvailability } from "@/types/dashboard";

type Tab = "Overview" | "Environment" | "Terminal" | "Deployments" | "Domain";
type Site = { id:number; name:string; status:string; repository_branch:string; domain:string; health_check_url:string|null; ssl_enabled:boolean; availability:SiteAvailability; };
type Service = { id:number; type:string; name:string; status:string; enabled:boolean; };
type Deployment = { id:number; status:string; commit_hash:string|null; branch:string; failed_step:string|null; };
type DeploymentLog = { id:number; step:string; level:string; message:string; exit_code:number|null; logged_at:string; };
const tabs:Tab[]=["Overview","Environment","Terminal","Deployments","Domain"];

export default function HostingPage() {
  const { siteId } = useParams<{siteId:string}>();
  const [site,setSite]=useState<Site|null>(null); const [services,setServices]=useState<Service[]>([]); const [deployments,setDeployments]=useState<Deployment[]>([]);
  const [tab,setTab]=useState<Tab>("Overview"); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  const [scope,setScope]=useState<"laravel"|"node">("laravel"); const [environment,setEnvironment]=useState(""); const [command,setCommand]=useState("php artisan about"); const [output,setOutput]=useState("");
  const [selected,setSelected]=useState<Deployment|null>(null); const [logs,setLogs]=useState<DeploymentLog[]>([]); const [loadingLogs,setLoadingLogs]=useState(false);
  const selectedId=selected?.id; const selectedStatus=selected?.status;

  async function load() { try { const [siteResponse,serviceResponse,deploymentResponse]=await Promise.all([api<{site:Site}>(`/api/sites/${siteId}`),api<{services:Service[]}>(`/api/sites/${siteId}/services`),api<{deployments:{data:Deployment[]}}>(`/api/sites/${siteId}/deployments`)]); setSite(siteResponse.site);setServices(serviceResponse.services);setDeployments(deploymentResponse.deployments.data);const visible=deploymentResponse.deployments.data.find((item)=>item.status==="queued"||item.status==="running")??deploymentResponse.deployments.data.find((item)=>item.status==="failed");if(visible){setTab("Deployments");void openLogs(visible);}}catch(exception){setError(exception instanceof Error?exception.message:"Unable to load application.");} }
  // The route id is the only input used for the initial project load.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{void load();},[siteId]);
  useEffect(()=>{const echo=deploymentEcho();if(!echo)return;const channel=echo.private(`hosting.site.${siteId}`);channel.listen(".deployment.updated",(event:{deployment:Deployment})=>{setDeployments((items)=>items.some((item)=>item.id===event.deployment.id)?items.map((item)=>item.id===event.deployment.id?event.deployment:item):[event.deployment,...items]);setSelected((item)=>item?.id===event.deployment.id?event.deployment:item);});channel.listen(".deployment.log.created",(event:{log:DeploymentLog})=>setLogs((items)=>items.some((item)=>item.id===event.log.id)?items:[...items,event.log]));return()=>echo.leave(`hosting.site.${siteId}`);},[siteId]);
  useEffect(()=>{if(!selectedId||!selectedStatus||!['queued','running'].includes(selectedStatus))return;const interval=window.setInterval(async()=>{try{const response=await api<{deployment:Deployment;logs:DeploymentLog[]}>(`/api/sites/${siteId}/deployments/${selectedId}/logs`);setSelected(response.deployment);setLogs(response.logs);setDeployments((items)=>items.map((item)=>item.id===response.deployment.id?response.deployment:item));}catch{/* Keep the current log view and retry while the deployment is active. */}},2000);return()=>window.clearInterval(interval);},[selectedId,selectedStatus,siteId]);
  async function act(action:()=>Promise<void>){setBusy(true);setError("");try{await action();}catch(exception){setError(exception instanceof Error?exception.message:"Action failed.");}finally{setBusy(false);}}
  async function openLogs(deployment:Deployment){setLoadingLogs(true);try{const response=await api<{deployment:Deployment;logs:DeploymentLog[]}>(`/api/sites/${siteId}/deployments/${deployment.id}/logs`);setSelected(response.deployment);setLogs(response.logs);}catch(exception){setError(exception instanceof Error?exception.message:"Unable to load deployment details.");}finally{setLoadingLogs(false);}}
  function downloadLogs(){if(!selected)return;const content=logs.map((log)=>`[${log.logged_at}] ${log.message}`).join("\n");const url=URL.createObjectURL(new Blob([content],{type:"text/plain"}));const link=document.createElement("a");link.href=url;link.download=`deployment-${selected.id}.log`;link.click();URL.revokeObjectURL(url);}
  if(!site)return <div className="rounded-3xl bg-white p-8">{error||"Loading application..."}</div>;
  return <DashboardPage><DashboardHero eyebrow="Application hosting · Deployment control" title={site.name} description="Manage deployments, environment variables, runtime tools, services, and the public domain from one application workspace." icon={Activity} contextLabel="Application address" contextValue={<a href={/^https?:\/\//i.test(site.domain)?site.domain:`http://${site.domain}`} target="_blank" rel="noopener noreferrer" className="hover:underline">{site.domain}</a>} action={<div className="flex gap-2">{selected?.status==="failed"&&<Button className="rounded-full border-white/20 bg-white/10 text-white hover:bg-white/20 hover:text-white" variant="outline" disabled={busy} onClick={()=>void act(async()=>{const response=await api<{deployment:Deployment}>(`/api/sites/${siteId}/deployments/${selected.id}/retry`,{method:"POST",body:"{}"});setDeployments((items)=>[response.deployment,...items]);setSelected(response.deployment);setLogs([]);setNotice("Retry queued.");})}><RotateCcw/>Retry</Button>}<Button disabled={busy} onClick={()=>void act(async()=>{await api(`/api/sites/${siteId}/deployments`,{method:"POST",body:"{}"});setNotice("Deployment queued.");await load();})} className="rounded-full bg-white text-[#2F4156] hover:bg-white/90"><Play/>Deploy</Button></div>} />
  <section className="rounded-3xl bg-white p-3 shadow-sm"><div className="flex gap-2 overflow-x-auto">{tabs.map((item)=><button key={item} onClick={()=>setTab(item)} className={`rounded-full px-4 py-2 text-sm ${tab===item?"bg-[#2F4156] text-white":"bg-[#F1F1F1]"}`}>{item}</button>)}</div></section>
  {error&&<p className="rounded-2xl bg-red-50 p-4 text-red-700">{error}</p>}{notice&&<p className="rounded-2xl bg-green-50 p-4 text-green-700">{notice}</p>}
  {tab==="Overview"&&<><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Availability" value={availabilityLabel(site.availability)} detail={availabilityDetail(site.availability)} icon={Globe2} tone="slate"/><MetricCard label="Deployment" value={site.status} detail="current state" icon={Activity} tone="lavender"/><MetricCard label="Branch" value={site.repository_branch} detail="deployment source" icon={GitBranch} tone="sky"/><MetricCard label="Domain" value={site.domain} detail="public address" icon={Globe2} tone="mist"/></section><CustomerServiceControls siteId={siteId} services={services} allowAdditionalNodeService onChanged={(service)=>setServices((items)=>items.some((item)=>item.id===service.id)?items.map((item)=>item.id===service.id?service:item):[service,...items])}/></>}
  {tab==="Environment"&&<Panel title="Environment variables"><div className="mb-4 flex gap-2"><Button variant={scope==="laravel"?"default":"outline"} onClick={()=>setScope("laravel")}>Laravel</Button><Button variant={scope==="node"?"default":"outline"} onClick={()=>setScope("node")}>Node.js</Button></div><p className="mb-3 text-sm text-[#567C8D]">Paste KEY=value entries. Sensitive values are stored securely.</p><textarea value={environment} onChange={(event)=>setEnvironment(event.target.value)} className="min-h-72 w-full rounded-2xl border p-4 font-mono text-sm" placeholder="APP_ENV=production"/><Button className="mt-4" onClick={()=>void act(async()=>{await api(`/api/sites/${siteId}/environments`,{method:"PUT",body:JSON.stringify({scope,content:environment})});setNotice("Environment saved.");})}>Save changes</Button></Panel>}
  {tab==="Terminal"&&<Panel title="Application tools"><p className="mb-4 text-sm text-[#567C8D]">Use approved maintenance commands. After a successful frontend build, BerryPanel automatically activates it by restarting the managed Node.js service. Examples: <code>php artisan about</code>, <code>npm run build</code>, or <code>git pull origin {site.repository_branch}</code>.</p><div className="flex flex-col gap-3 md:flex-row"><Input value={command} onChange={(event)=>setCommand(event.target.value)}/><Button onClick={()=>void act(async()=>{const response=await api<{result:{output:string;exit_code:number}}>(`/api/sites/${siteId}/terminal`,{method:"POST",body:JSON.stringify({command,scope:"laravel",confirmed:command.includes("migrate")})});setOutput(`${response.result.output}\n\nExit code: ${response.result.exit_code}`);})}><Terminal/>Run</Button></div><pre className="mt-5 min-h-64 overflow-auto rounded-2xl bg-[#2F4156] p-5 text-sm text-green-300">{output||"Command output will appear here."}</pre></Panel>}
  {tab==="Deployments"&&<Panel title="Deployment history"><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><div className="space-y-3">{deployments.map((deployment)=><button type="button" key={deployment.id} onClick={()=>void openLogs(deployment)} className={`w-full rounded-2xl border p-4 text-left ${selected?.id===deployment.id?"border-[#2F4156] bg-[#F1F1F1]":"border-[#2F4156]/10"}`}><div className="flex justify-between"><span>Deployment #{deployment.id}</span><span className="text-sm">{deployment.status}</span></div>{deployment.failed_step&&<p className="mt-2 text-sm text-red-700">Needs attention: {deployment.failed_step}</p>}</button>)}</div><div className="flex h-[420px] flex-col overflow-hidden rounded-2xl bg-[#2F4156] p-4 text-white"><div className="flex shrink-0 justify-between border-b border-white/10 pb-3"><span>{selected?`Deployment #${selected.id} details`:"Select a deployment"}</span><span className="flex gap-2"><Button size="sm" variant="outline" disabled={!selected||loadingLogs} onClick={()=>selected&&void openLogs(selected)}><RefreshCw/>Refresh</Button><Button size="sm" variant="outline" disabled={!logs.length} onClick={downloadLogs}><Download/>Download</Button></span></div><div className="mt-4 min-h-0 flex-1 space-y-2 overflow-y-auto font-mono text-xs">{logs.map((log)=><p key={log.id} className={log.level==="error"?"text-red-300":log.level==="warning"?"text-amber-300":"text-green-200"}>{log.message}{log.exit_code!==null&&` (exit ${log.exit_code})`}</p>)}</div></div></div></Panel>}
  {tab==="Domain"&&<Panel title="Domain"><div className="grid gap-4 md:grid-cols-2"><div><Label>Application address</Label><Input className="mt-2" value={site.domain} disabled/></div><div><Label>Secure connection</Label><div className="mt-2 rounded-xl bg-[#F1F1F1] p-3 text-sm">{site.ssl_enabled?"Enabled":"Managed automatically"}</div></div></div></Panel>}</DashboardPage>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-3xl bg-white p-6 shadow-sm lg:p-8"><h2 className="mb-6 text-2xl font-semibold">{title}</h2>{children}</section>}
