<?php
namespace App\Http\Controllers;
use App\Models\Site; use App\Models\SiteService; use App\Services\Hosting\AuditLogger; use App\Services\Hosting\SupervisorManager; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use RuntimeException;
class SiteServiceController extends Controller {
 public function index(Request $r,Site $site):JsonResponse{$this->authorize('view',$site);return response()->json(['services'=>$site->services()->latest()->get(),'templates'=>$this->templates()]);}
 public function store(Request $r,Site $site,SupervisorManager $manager,AuditLogger $audit):JsonResponse{$this->authorize('update',$site);$v=$r->validate($this->rules());try{$manager->validateCommand($v['command'],$v['type']);$s=$site->services()->create($v);$manager->apply($s);}catch(RuntimeException $e){return response()->json(['message'=>$e->getMessage()],422);}$audit->record('service.created',$site,$r->user(),['service_id'=>$s->id]);return response()->json(['service'=>$s],201);}
 public function action(Request $r,Site $site,SiteService $service,SupervisorManager $manager,AuditLogger $audit):JsonResponse{$this->authorize('update',$site);abort_unless($service->site_id===$site->id,404);$v=$r->validate(['action'=>['required','in:start,stop,restart,enable,disable']]);if(in_array($v['action'],['enable','disable'])){$service->update(['enabled'=>$v['action']==='enable']);$manager->apply($service);}else{$manager->action($service,$v['action']);}$audit->record('service.'.$v['action'],$site,$r->user(),['service_id'=>$service->id]);return response()->json(['service'=>$service->fresh()]);}
 private function rules():array{return ['name'=>['required','string','max:80'],'type'=>['required','in:queue,horizon,reverb,scheduler,node'],'working_directory'=>['required','string','max:255','regex:/^\/(?!.*\.\.)/'],'command'=>['required','string','max:255'],'processes'=>['required','integer','between:1,20'],'restart_policy'=>['required','in:always,on-failure,never'],'max_retries'=>['required','integer','between:0,20'],'stop_timeout'=>['required','integer','between:1,300'],'environment_source'=>['required','in:laravel,node,none'],'log_file'=>['nullable','string','max:255'],'enabled'=>['boolean']];}
 private function templates():array{return [['type'=>'queue','name'=>'Queue Worker','command'=>'php artisan queue:work','working_directory'=>'/backend'],['type'=>'horizon','name'=>'Laravel Horizon','command'=>'php artisan horizon','working_directory'=>'/backend'],['type'=>'reverb','name'=>'Laravel Reverb','command'=>'php artisan reverb:start','working_directory'=>'/backend'],['type'=>'scheduler','name'=>'Laravel Scheduler','command'=>'php artisan schedule:work','working_directory'=>'/backend'],['type'=>'node','name'=>'Node.js Production Server','command'=>'npm run start','working_directory'=>'/frontend']];}
}
